# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@taplo/lsp-0.1.8" = {
      name = "_at_taplo_slash_lsp";
      packageName = "@taplo/lsp";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@taplo/lsp/-/lsp-0.1.8.tgz";
        sha512 = "EUoR67Jgt4AB7FVOLFcKQu92iaqCnQd9OfOthCqJt2GuD5jV8F7FPE9pJqhzzfAeQD6DZSxayToguy3YCdDkUA==";
      };
    };
    "node-fetch-2.6.6" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.6.tgz";
        sha512 = "Z8/6vRlTUChSdIgMa51jxQ4lrw/Jy5SOW10ObaA47/RElsAN2c5Pn8bTgFGWn/ibwzXTE8qwr1Yzx28vsecXEA==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha1 = "8184fd347dac9cdc185992f3a6622e14b9d9ab6a";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha1 = "24534275e2a7bc6be7bc86611cc16ae0a5654871";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha1 = "966454e8765462e37644d3626f6742ce8b70965d";
      };
    };
  };
in
{
  coc-toml = nodeEnv.buildNodePackage {
    name = "coc-toml";
    packageName = "coc-toml";
    version = "1.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-toml/-/coc-toml-1.1.0.tgz";
      sha512 = "EpgXFBmSiusHCeBPfJIQlR89IGUxkL7FJqajM5YTFecNj2BpOl2AEmXZcc6gSn4pNCmWcEzC/B2cUcJMhSsKNQ==";
    };
    dependencies = [
      sources."@taplo/lsp-0.1.8"
      sources."node-fetch-2.6.6"
      sources."tr46-0.0.3"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "toml extension for coc.nvim";
      homepage = "https://github.com/kkiyama117/coc-toml#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
